name = "zhiyinx-xyz"
main = "src/index.js"
compatibility_date = "2026-06-16"
workers_dev = true
account_id = "5231e27427d1d2a36acf213a56d09110"

[[d1_databases]]
binding = "DB"
database_name = "zhiyinx-db"
database_id = "f0a155e4-8094-43a6-9745-58f159ef2d14"
remote = true

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
