name = "zhiyinx-xyz"
main = "src/index.ts"
compatibility_date = "2026-06-16"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "zhiyinx-db"
database_id = "f0a155e4-8094-43a6-9745-58f159ef2d14"
remote = true
